### ISSUE TITLE
Feat: Implement PrimaryMedication Feature

### ISSUE THREAD

**Issue by yeniful** [yeniful/Tracka#1]
![이슈](https://github.com/user-attachments/assets/d0438e8f-408a-4be8-8f49-30ad554566aa)

# Description
Implement functionality to create a PrimaryMedication routine in the PrimaryMedicationView and display it in the TodayView.

# Tasks
- [x] Create `TodayView`:
  - Display the medication routines that need to be taken today
- [x] Create `PrimaryMedication` Model:
  - Define properties such as medication name, dosage, and intake time.
- [x] Create `PrimaryMedicationView`:
  - Implement using a temporary UI, and apply the final UI design once it becomes available.
  - Implement a NavigationLink to navigate from `TodayView` to `PrimaryMedicationView`.
  - Implement functionality to display abdominal routines with toggle switches to enable or disable routines
- [x] Create `AddPrimaryMedicationView`
  - Implement logic to create a PrimaryMedication routine in the `AddPrimaryMedicationView`
- [x] Create `AddPrimaryMedicationDetailView`
  - Implement a screen to display detailed information for each abdominal routine
# Acceptance Criteria
- [ ] The `PrimaryMedication` model is created and can properly store/manage data.
- [x] `PrimaryMedicationView` is correctly displayed
